title: My Awesome Notes
author: GitHub User
email: your-email@domain.com
description: > # this means to ignore newlines until "baseurl:"
  Some random notes.
  I'm only simple human being, if I'm wrong somewhere - leave a comment - happy to learn!

# social links
twitter_username: your-twitter-handle # DO NOT include the @ character, or else the build will fail!
github_username:  your-github-handle # DO NOT include the @ character, or else the build will fail!

show_excerpts: true # set to false to remove excerpts on the homepage
